name: Deploy Backend to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # Set up SSH agent with the private key from GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add the Lightsail server to known_hosts to avoid host key verification failure
      - name: Add Lightsail instance to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

      # Install dependencies and build your project
      - name: Install dependencies
        run: |
          cd backend
          npm install
          npm run build

      # Deploy the code to the Lightsail server
      - name: Deploy to AWS Lightsail
        run: |
          ssh bitnami@${{ secrets.LIGHTSAIL_IP }} "rm -rf /home/bitnami/Quizmate/backend/dist"
          scp -r ./backend/dist/ bitnami@${{ secrets.LIGHTSAIL_IP }}:/home/bitnami/Quizmate/backend
          ssh bitnami@${{ secrets.LIGHTSAIL_IP }} "cd /home/bitnami/Quizmate/backend && npm install && pm2 restart all"
